name: ${project.name}
main: vg.civcraft.mc.namelayer.NameLayerPlugin
version: ${project.version}
author: Rourke750
depend: [CivModCore]
softdepend: [Mercury]
description: NameLayer handles groups creation and management, in addition to name changes. Once you have connected to Civcraft with a name, it is permanently yours. If a name is already taken, then NameLayer will add a number to the name.
commands:
   nlag:
    aliases: [nlacceptinvite, nlacceptgroup, acceptgroup, accept]
   nlcg:
    aliases: [nlcreategroup, create, ctcreate, ctc, ng, newgroup, creategroup]
   nldg:
    aliases: [nldeletegroup, ctdel, ctdelete, deletegroup, delete]
   nldig:
    aliases: [nldisiplinegroup, nldisablegroup, nldisable]
    permission: namelayer.admin
   nlgls:
    aliases: [nlglobalstats]
   nlgs:
    aliases: [nlgroupstats]
   nlid:
    aliases: [nlinfodump]
   nlip:
    aliases: [nlinviteplayer, nlinvite, invite, ctallow]
   nljg:
    aliases: [nljoingroup, nljoin, join, ctjoin]
   nllg:
    aliases: [nllistgroups, nllistg, listgroups, ctgroups]
   nllm:
    aliases: [nllistmembers, nllistm, listmembers]
   nllp:
    aliases: [nllistpermissions, nllistperms, perms]
   nlpp:
    aliases: [nlpromoteplayer, nlpromote, promote]
   nlmg:
    aliases: [nlmergegroups, nlmerge, merge]
   nlmp:
    aliases: [nlmodifyperms, nlmodifypermissions, nlmodperms]
   nlrm:
    aliases: [nlremovemember, nlremove, nlkick, remove]
   nlri:
    aliases: [nlrevokeinvite, nluninvite, revoke]
   nlrsg:
   nlsp:
    aliases: [nlsetpassword, nlsetpass]
   nltg:
    aliases: [nltransfergroup, nltransfer, transfer]
   nlleg:
    aliases: [nlleavegroup, nlleave, leave]
   nllgt:
    aliases: [nllistgrouptypes, nllistgtypes]
   nllpt:
    aliases: [nllistplayertypes, nllistptypes]
   nllci:
    aliases: [nllistcurrentinvites, nllistinvites]
   nltaai:
    aliases: [nlautoacceptinvites, nlautoaccept, autoaccept]
   nlcpn:
      permission: namelayer.admin
   nlsdg:
    aliases: [nlsetdefaultgroup, nlsetdefault]
   nlgdg:
    aliases: [nlgetdefaultgroup, nlgetdefault]
permissions:
   namelayer.admin:
      default: op
