name: ${project.name}
main: vg.civcraft.mc.namelayer.NameLayerPlugin
version: ${project.version}
author: Rourke750
depend: [CivModCore]
softdepend: [Mercury]
description: NameLayer handles groups creation and management, in addition to name changes. Once you have connected to Civcraft with a name, it is permanently yours. If a name is already taken, then NameLayer will add a number to the name.
commands:
   nlag:
    aliases: [nlacceptinvite, nlacceptgroup, accept, acceptinvite]
   nlcg:
    aliases: [nlcreategroup, creategroup]
   nldg:
    aliases: [nldeletegroup, deletegroup]
   nldig:
    aliases: [nldisiplinegroup, nldisablegroup, nldisable]
    permission: namelayer.admin
   nlgls:
    aliases: [nlglobalstats]
   nlgs:
    aliases: [nlgroupstats]
   nlid:
    aliases: [nlinfodump]
   nlip:
    aliases: [nlinviteplayer, nlinvite, invite]
   nljg:
    aliases: [nljoingroup, nljoin, join]
   nllg:
    aliases: [nllistgroups, nllistg, listgroups]
   nllm:
    aliases: [nllistmembers, nllistm, listmembers]
   nllcm:
   nllp:
    aliases: [nllistpermissions, nllistperms, listpermissions]
   nlpp:
    aliases: [nlpromoteplayer, nlpromote, promote]
   nlmg:
    aliases: [nlmergegroups, nlmerge, mergegroup]
   nlmp:
    aliases: [nlmodifyperms, nlmodifypermissions, nlmodperms, modifypermissions]
   nlrm:
    aliases: [nlremovemember, nlremove, nlkick, kickmember, removemember]
   nlri:
    aliases: [nlrevokeinvite, nluninvite, revokeinvite]
   nllink:
   nlunlink:
   nllsg:
   nlsp:
    aliases: [nlsetpassword, nlsetpass, setpassword]
   nltg:
    aliases: [nltransfergroup, nltransfer, transfergroup]
   nlleg:
    aliases: [nlleavegroup, nlleave, leavegroup]
   nllgt:
    aliases: [nllistgrouptypes, nllistgtypes, listgrouptypes]
   nllpt:
    aliases: [nllistplayertypes, nllistptypes, listplayertypes]
   nllci:
    aliases: [nllistcurrentinvites, nllistinvites, listinvites]
   nltaai:
    aliases: [nlautoacceptinvites, nlautoaccept]
   nlcpn:
      permission: namelayer.admin
   nlsdg:
    aliases: [nlsetdefaultgroup, nlsetdefault, setdefaultgroup]
   nlgdg:
    aliases: [nlgetdefaultgroup, nlgetdefault, getdefaultgroup]
permissions:
   namelayer.admin:
      default: op
