name: ${project.name}
main: vg.civcraft.mc.namelayer.NameLayerPlugin
version: ${project.version}
author: Rourke750
depend: [CivModCore]
softdepend: [Mercury]
description: NameLayer handles groups creation and management, in addition to name changes. Once you have connected to Civcraft with a name, it is permanently yours. If a name is already taken, then NameLayer will add a number to the name.
commands:
   nlag:
    aliases: [nlacceptinvite, nlacceptgroup]
   nlcg:
    aliases: [nlcreategroup]
   nldg:
    aliases: [nldeletegroup]
   nldig:
    aliases: [nldisiplinegroup, nldisablegroup, nldisable]
    permission: namelayer.admin
   nlgls:
    aliases: [nlglobalstats]
   nlgs:
    aliases: [nlgroupstats]
   nlid:
    aliases: [nlinfodump]
   nlip:
    aliases: [nlinviteplayer, nlinvite]
   nljg:
    aliases: [nljoingroup, nljoin]
   nllg:
    aliases: [nllistgroups, nllistg]
   nllm:
    aliases: [nllistmembers, nllistm]
   nllcm:
   nllp:
    aliases: [nllistpermissions, nllistperms]
   nlpp:
    aliases: [nlpromoteplayer, nlpromote]
   nlmg:
    aliases: [nlmergegroups, nlmerge]
   nlmp:
    aliases: [nlmodifyperms, nlmodifypermissions, nlmodperms]
   nlrm:
    aliases: [nlremovemember, nlremove, nlkick]
   nlri:
    aliases: [nlrevokeinvite, nluninvite]
   nllink:
   nlunlink:
   nllsg:
   nlsp:
    aliases: [nlsetpassword, nlsetpass]
   nltg:
    aliases: [nltransfergroup, nltransfer]
   nlleg:
    aliases: [nlleavegroup, nlleave]
   nllgt:
    aliases: [nllistgrouptypes, nllistgtypes]
   nllpt:
    aliases: [nllistplayertypes, nllistptypes]
   nllci:
    aliases: [nllistcurrentinvites, nllistinvites]
   nltaai:
    aliases: [nlautoacceptinvites, nlautoaccept]
   nlcpn:
      permission: namelayer.admin
   nlsdg:
    aliases: [nlsetdefaultgroup, nlsetdefault]
   nlgdg:
    aliases: [nlgetdefaultgroup, nlgetdefault]
permissions:
   namelayer.admin:
      default: op
