name: ${project.name}
main: vg.civcraft.mc.namelayer.NameLayerPlugin
version: ${project.version}
author: Rourke750
authors: [BlackXnt, Maxopoly, ProgrammerDan, Tyrothalos, Scuwr]
depend: [CivModCore]
softdepend: [Mercury]
description: NameLayer handles groups creation and management, in addition to name changes. Once you have connected to Civcraft with a name, it is permanently yours. If a name is already taken, then NameLayer will add a number to the name.
commands:
   nlag:
    aliases: [nlacceptinvite, nlacceptgroup, acceptinvite, acceptgroup, accept]
   nlcg:
    aliases: [nlcreategroup, creategroup]
   nldg:
    aliases: [nldeletegroup, deletegroup]
   nldig:
    aliases: [nldisiplinegroup, nldisablegroup, nldisable]
    permission: namelayer.admin
   nlgls:
    aliases: [nlglobalstats]
   nlgs:
    aliases: [nlgroupstats]
   nlid:
    aliases: [nlinfodump]
   nlip:
    aliases: [nlinviteplayer, nlinvite, invite]
   nljg:
    aliases: [nljoingroup, nljoin]
   nllg:
    aliases: [nllistgroups, nllistg, listgroups]
   nllm:
    aliases: [nllistmembers, nllistm, listmembers]
   nllcm:
   nllp:
    aliases: [nllistpermissions, nllistperms, listpermissions]
   nlpp:
    aliases: [nlpromoteplayer, nlpromote, promoteplayer]
   nlmg:
    aliases: [nlmergegroups, nlmerge, mergegroup, mergegroups]
   nlmp:
    aliases: [nlmodifyperms, nlmodifypermissions, nlmodperms, modifypermissions]
   nlrm:
    aliases: [nlremovemember, nlremove, nlkick, kickmember, removemember]
   nlri:
    aliases: [nlrevokeinvite, nluninvite, revoke, uninvite, revokeinvite]
   nllink:
   nlunlink:
   nllsg:
   nlsp:
    aliases: [nlsetpassword, nlsetpass, setpass, setpassword]
   nltg:
    aliases: [nltransfergroup, nltransfer, transfergroup]
   nlleg:
    aliases: [nlleavegroup, nlleave, leavegroup]
   nllgt:
    aliases: [nllistgrouptypes, nllistgtypes, listgrouptypes]
   nllpt:
    aliases: [nllistplayertypes, nllistptypes, listplayertypes]
   nllci:
    aliases: [nllistcurrentinvites, nllistinvites, invites, listinvites]
   nltaai:
    aliases: [nlautoacceptinvites, nlautoaccept, autoaccept]
   nlcpn:
    permission: namelayer.admin
   nlsdg:
    aliases: [nlsetdefaultgroup, nlsetdefault, setdefault, setdefaultgroup]
   nlgdg:
    aliases: [nlgetdefaultgroup, nlgetdefault, getdefaultgroup]
   nlun:
    aliases: [updatename]
   nlsbl:
    aliases: [showblacklist, listblacklist]
   nlbl:
    aliases: [blacklist, addblacklist]
   nlubl:
    aliases: [removeblacklist, unblacklist]    
   nl:
   nlapt:
    aliases: [nlcpt, addplayertype, nladdplayertype, createplayertype]
   nldpt:
    aliases: [removeplayertype, nldeleteplayertype, deleteplayertype]
   nlrpt:
    aliases: [changeplayertypename, renameplayertype, nlrenameplayertype]
       
permissions:
   namelayer.admin:
      default: op
